import os
import json
from pathlib import Path
from google.analytics.data_v1beta import BetaAnalyticsDataClient
from google.analytics.data_v1beta.types import (
    DateRange, Dimension, Metric, RunReportRequest, FilterExpression, Filter
)

class AnalyticsAgent: 
    def __init__(self):
        # Dynamically locate the root directory of the project
        base_dir = Path(__file__).resolve().parent.parent
        self.creds_path = base_dir / "credentials.json"
        
        if not self.creds_path.exists():
            # Crucial: Don't crash the whole app, but log it clearly
            print(f"ERROR: credentials.json not found at {self.creds_path}")
            self.client = None
        else:
            os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = str(self.creds_path)
            self.client = BetaAnalyticsDataClient()

    ALLOWED_METRICS = ["activeUsers", "sessions", "screenPageViews", "eventCount", "newUsers"]
    ALLOWED_DIMENSIONS = ["date", "pagePath", "country", "deviceCategory", "sessionSource"]

    def validate_plan(self, plan: dict):
        """Sanitize the LLM output before it hits the Google API."""
        validated_metrics = [m for m in plan.get("metrics", []) if m in self.ALLOWED_METRICS]
        validated_dimensions = [d for d in plan.get("dimensions", []) if d in self.ALLOWED_DIMENSIONS]
        
        # Fallback if LLM misses everything
        if not validated_metrics: validated_metrics = ["activeUsers"]
        if not validated_dimensions: validated_dimensions = ["date"]
        
        plan["metrics"] = validated_metrics
        plan["dimensions"] = validated_dimensions
        return plan
    
    

    def run(self, property_id: str, reporting_plan: dict):

        if property_id == "TEST":
            print("⚠️ Using TEST Data for Fusion Verification")
            # We return paths that look like your website to see if they match the Sheet
            return [
                {"pagePath": "/", "screenPageViews": 5000, "activeUsers": 1200}, 
                {"pagePath": "/blog/", "screenPageViews": 850, "activeUsers": 300},
                # Add a random path to prove the "Left Join" works (this one won't have SEO data)
                {"pagePath": "/random-landing-page", "screenPageViews": 100, "activeUsers": 10}
            ]
        # ---------------------------------------------------------

        """
        Executes the query based on a plan generated by the LLM.
        Expected plan format: 
        {
            "metrics": ["activeUsers", "sessions"],
            "dimensions": ["date", "pagePath"],
            "days_ago": 14,
            "filter_path": "/pricing" (optional)
        }
        """
        try:
            # 1. Build the Request
            request = RunReportRequest(
                property=f"properties/{property_id}",
                dimensions=[Dimension(name=d) for d in reporting_plan.get("dimensions", [])],
                metrics=[Metric(name=m) for m in reporting_plan.get("metrics", [])],
                date_ranges=[DateRange(
                    start_date=f"{reporting_plan.get('days_ago', 14)}daysAgo", 
                    end_date="today"
                )],
            )

            # 2. Apply Page Path filtering if implied in query
            if reporting_plan.get("filter_path"):
                request.dimension_filter = FilterExpression(
                    filter=Filter(
                        field_name="pagePath",
                        string_filter=Filter.StringFilter(value=reporting_plan["filter_path"])
                    )
                )

            # 3. Execute
            response = self.client.run_report(request)
            return self._process_response(response)

        except Exception as e:
            error_str = str(e).lower()
            # If GA4 complains about metrics, force a fallback to safe basics
            if "metric" in error_str and ("not supported" in error_str or "invalid" in error_str):
                print("⚠️ Invalid metric detected by GA4. Retrying with safe defaults...")
                # Overwrite with guaranteed safe metrics
                reporting_plan["metrics"] = ["activeUsers", "screenPageViews"]
                # Recursive call: Try again with the fixed plan
                return self.run(property_id, reporting_plan)
            # ---------------------------------------
            return {"error": f"GA4 API Error: {str(e)}"}

    def _process_response(self, response):
        if not response.rows:
            return "No data found for the requested period."

        data = []
        # Limit to top 50 rows to prevent LLM context overflow
        for row in response.rows[:50]: 
            row_data = {}
            for i, val in enumerate(row.dimension_values):
                # Handle empty dimensions
                header = response.dimension_headers[i].name
                row_data[header] = val.value if val.value else "unknown"
                
            for i, val in enumerate(row.metric_values):
                # Ensure metrics are treated as numbers
                header = response.metric_headers[i].name
                try:
                    row_data[header] = float(val.value)
                except ValueError:
                    row_data[header] = 0
                    
            data.append(row_data)
        return data